package com.todolab.task.repository;

import com.todolab.support.RepositoryTestSupport;
import com.todolab.task.domain.Task;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

class TaskRepositoryTest extends RepositoryTestSupport {

    @Autowired
    TaskRepository taskRepository;

    @Test
    @DisplayName("save() 호출 시 Task가 정상적으로 저장된다")
    void save_success() {
        // given
        Task task = Task.builder()
                .title("hello")
                .description("desc")
                .taskDate(LocalDate.of(2025, 11, 27))
                .taskTime(LocalTime.of(10, 30))
                .build();

        // when
        Task saved = taskRepository.save(task);
        flushAndClear();

        // then
        assertThat(saved.getId()).isNotNull();
        assertThat(saved.getTitle()).isEqualTo("hello");
        assertThat(saved.getDescription()).isEqualTo("desc");
        assertThat(saved.getTaskDate()).isEqualTo(LocalDate.of(2025, 11, 27));
        assertThat(saved.getTaskTime()).isEqualTo(LocalTime.of(10, 30));
    }

    @Test
    @DisplayName("@PrePersist 를 통해 createdAt 이 자동으로 세팅된다")
    void createdAt_autoGenerated() {
        // given
        Task task = Task.builder()
                .title("created test")
                .description("desc")
                .taskDate(LocalDate.of(2025, 11, 30))
                .taskTime(LocalTime.of(9, 0))
                .build();

        // when
        Task saved = taskRepository.save(task);
        flushAndClear();

        // then
        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getCreatedAt()).isBeforeOrEqualTo(LocalDateTime.now());
    }
}