spring:
  profiles:
    active: local

  threads:
    virtual:
      enabled: true

app:
  cors:
    allowed-origins: http://localhost:8081,http://localhost:8090

  batch:
    scheduler:
      enabled: false
