-- TASK
CREATE TABLE TASK (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    START_AT DATETIME NULL,
    END_AT DATETIME NULL,
    ALL_DAY BOOLEAN NOT NULL DEFAULT FALSE,
    CATEGORY VARCHAR(255) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID)
);