-- TASK
CREATE TABLE IF NOT EXISTS TASK (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(500),
    TASK_DATE DATE,
    TASK_TIME TIME,
    CREATED_AT TIMESTAMP
);